name: Build Geode Mod
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          platform: win       # Mudado de target para platform (e deixado em minúsculo)
        - name: Android32
          os: ubuntu-latest
          platform: android32 # Mudado de target para platform
        - name: Android64
          os: ubuntu-latest
          platform: android64 # Mudado de target para platform

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main  
      with:
        # CORREÇÃO CRUCIAL: Trocado 'target:' por 'platform:' para bater com a nova CLI do Geode!
        platform: ${{ matrix.config.platform }}