name: Build Geode Mod
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          platform: win
        - name: Android32
          os: ubuntu-latest
          platform: android32
        - name: Android64
          os: ubuntu-latest
          platform: android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4

    # CORREÇÃO DEFINITIVA: Removemos o passo de setup que foi deletado do GitHub 
    # E atualizamos a Action de Build para a '@v3', que faz o setup automático e aceita o parâmetro 'platform'!
    - name: Build Mod
      uses: geode-sdk/build-geode-mod@v3  
      with:
        platform: ${{ matrix.config.platform }}